### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xxnbyy** [nimble-technology/nimble-miner-public#4]
go install -mod=readonly -tags 'netgo' -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=nimble-network -X github.com/cosmos/cosmos-sdk/version.AppName=nimble-networkd -X github.com/cosmos/cosmos-sdk/version.Version= -X github.com/cosmos/cosmos-sdk/version.Commit=d77f652f874ca786d952abdc82c74e4444d1e3e7 -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo -w -s' -trimpath ./cmd/nimble-networkd
/root/go/pkg/mod/github.com/cosmos/ibc-go/v8@v8.0.0/modules/core/02-client/types/params.go:5:2: package slices is not in GOROOT (/usr/share/go/src/slices)
make: *** [Makefile:98: install] Error 1

**Comment by Haniamin90** [comment]
need Go version 1.22 minimum
